<h1><?php echo $this->translate('Loaded modules') ?></h1>

<table class="table table-condensed">
    <tr>
        <th>Module</th>
        <th>Local version</th>
        <th>Remote hash</th>
        <th>Status</th>
    </tr>
    <?php foreach ($this->modules as $name => $data) : ?>
    <tr>
        <td><?php echo $name; ?></td>
        <td><?php echo $data['version']; ?></td>
        <td><?php echo $data['remoteHash']; ?></td>
        <td><?php echo $data['status']; ?></td>
    </tr>
    <?php endforeach; ?>
</table>