<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('AtAdmin Admin Panel')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Styles -->
        <?php echo $this->headLink()->prependStylesheet($this->basePath() . '/css/at-admin/admin.css')
                             ->prependStylesheet('//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile('//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/js/bootstrap.min.js')
                               ->prependFile('//code.jquery.com/jquery.min.js')
                               ->prependFile('//html5shiv.googlecode.com/svn/trunk/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))?>

    </head>

    <body>

        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('zfcadmin') ?>">AtAdmin</a>
                    <div class="nav-collapse">
                        <ul class="nav">
                            <?php foreach ($this->navigation('admin_navigation')->getContainer() as $item): ?>
                                <?php if ($item->hasPages()): ?>
                                <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                            <?php echo $this->translate($item->getLabel()) ?>
                                            <b class="caret"></b>
                                        </a>
                                        <ul class="dropdown-menu">
                                            <?php foreach ($item->getPages() as $page): ?>
                                            <li><a href="<?php echo $page->getHref() ?>"><?php echo $this->translate($page->getLabel()) ?></a></li>
                                            <?php endforeach; ?>
                                        </ul>
                                    </li>
                                <?php else: ?>
                                    <li><a href="<?php echo $item->getHref() ?>"><?php echo $this->translate($item->getLabel()) ?></a></li>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>

        <div class="container">

            <?php echo $this->content; ?>

            <hr>

            <footer>
                 <p>Powered by <a href="https://github.com/atukai/AtAdmin" target="_blank">AtAdmin</a>.</p>
            </footer>

        </div> <!-- /container -->

        <?php echo $this->inlineScript() ?>
    </body>
</html>
