<?php echo $this->doctype(); ?>
<html lang="es">
    <head>
        <meta charset="utf-8">
	    <?php echo $this->headTitle('ZfcAdmin - Zend Framework 2 Admin Interface')->setSeparator(' - ')->setAutoEscape(false) ?>
	
	    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
	
	    <!-- Le styles -->
	    <?php echo $this->headLink()->prependStylesheet($this->basePath() . '/css/style.css')->prependStylesheet('//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css') ?>
	
	    <!-- Scripts -->
	    <?php echo $this->headScript()->prependFile('//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js')
	                                  ->prependFile('//code.jquery.com/jquery.min.js')
	                                  ->prependFile('//html5shiv.googlecode.com/svn/trunk/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',)) ?>

    </head>

    <body>

        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                <div class="container">
                    <div class="navbar-header">
	                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
	                        <span class="icon-bar"></span>
	                        <span class="icon-bar"></span>
	                        <span class="icon-bar"></span>
	                    </button>
	                    <a class="navbar-brand" href="<?php echo $this->url('zfcadmin') ?>"><?php echo $this->translate('Joacub Admin') ?></a>
	                </div>
                  <div class="collapse navbar-collapse">
                    	<ul class="nav navbar-nav">
                            <?php foreach ($this->navigation('admin_navigation')->getContainer() as $item): ?>
                                <?php if ($item->hasPages()): ?>
                                <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                            <?php echo $this->translate($item->getLabel()) ?>
                                            <b class="caret"></b>
                                        </a>
                                        <ul class="dropdown-menu">
                                            <?php foreach ($item->getPages() as $page): ?>
                                            <li><a href="<?php echo $page->getHref() ?>"><?php echo $page->getLabel() ? $this->translate($page->getLabel()) : $page->getLabel() ?></a></li>
                                            <?php endforeach; ?>
                                        </ul>
                                    </li>
                                <?php else: ?>
                                    <li><a href="<?php echo $item->getHref() ?>"><?php echo $this->translate($item->getLabel()) ?></a></li>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
        </nav>

        <div class="container">

            <?php echo $this->content; ?>

            <hr>

            <footer>
                 <p>Powered by <a href="https://github.com/joacub" target="_blank">Joacub Admin</a>.</p>
            </footer>

        </div> <!-- /container -->

        <?php echo $this->inlineScript() ?>
    </body>
</html>
